steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/dev-cloudrun-tools/srt-formatter:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dev-cloudrun-tools/srt-formatter:$COMMIT_SHA']
  # Tag the image as 'latest'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/dev-cloudrun-tools/srt-formatter:$COMMIT_SHA', 'gcr.io/dev-cloudrun-tools/srt-formatter:latest']
  # Push the 'latest' tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dev-cloudrun-tools/srt-formatter:latest']
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - 'srt-formatter'
      - '--image'
      - 'gcr.io/dev-cloudrun-tools/srt-formatter:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-south1'
      - '--allow-unauthenticated'
      - '--project'
      - 'dev-cloudrun-tools'
    entrypoint: 'gcloud'

images:
  - 'gcr.io/dev-cloudrun-tools/srt-formatter:$COMMIT_SHA'
  - 'gcr.io/dev-cloudrun-tools/srt-formatter:latest'

options:
  logging: CLOUD_LOGGING_ONLY
