steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/dev-cloudrun-tools/srt-formatter:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dev-cloudrun-tools/srt-formatter:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/dev-cloudrun-tools/srt-formatter:$COMMIT_SHA', 'gcr.io/dev-cloudrun-tools/srt-formatter:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dev-cloudrun-tools/srt-formatter:latest']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - srt-formatter
      - --image
      - gcr.io/dev-cloudrun-tools/srt-formatter:$COMMIT_SHA
      - --region
      - us-central1
      - --platform
      - managed
      - --allow-unauthenticated
      - --timeout
      - 300s
images:
  - 'gcr.io/dev-cloudrun-tools/srt-formatter:$COMMIT_SHA'
  - 'gcr.io/dev-cloudrun-tools/srt-formatter:latest'
options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: '614638457986-compute@developer.gserviceaccount.com'
