steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/srt-formatter:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/srt-formatter:$COMMIT_SHA']

  # Tag the image as 'latest'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/srt-formatter:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/srt-formatter:latest']

  # Push the 'latest' tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/srt-formatter:latest']

images:
  - 'gcr.io/$PROJECT_ID/srt-formatter:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/srt-formatter:latest' 
